### PR TITLE
added defined resources for network and user configuration

### PR DESCRIPTION
**Pull request by ripclawffb**
also added documentation and examples for network and user defined resources

### CODE REVIEW

**Comment by jhoblitt** [comment]
The type declarations break compat with puppet 3.x.  Could you convert these to `validate_` functions?  I think we need to support 3.x for a bit longer.

**Comment by ripclawffb** [comment]
I have made the requested changes. Thanks!

**Comment by ripclawffb** [comment]
I have made the changes. Thanks.





On Tue, Jun 21, 2016 at 6:20 PM -0700, "Joshua Hoblitt" <notifications@github.com> wrote:





The type declarations break compat with puppet 3.x.  Could you convert these to `validate_` functions?  I think we need to support 3.x for a bit longer.

---

**Comment by elisiano** [comment]
I didn't test it but this PR looks amazing! +1

**Comment by jhoblitt** [comment]
The travis failure was due to ruby 1.8.7, which can be ignored (this module needs a plumbing update).

This looks pretty reasonable to me.  Would you be willing to add a few rspec unit tests?

**Comment by ripclawffb** [comment]
Sure, I’ll read up on it and see if I can write some tests. I’ve never done it before.

**Comment by ripclawffb** [comment]
I created the rspec tests for the new features and also incorporated some tests/changes from Pat. I had to remove the interface type setting since it wasn't working as expected. I think we can revisit after these initial features are merged. Appreciate the help.

**Comment by jhoblitt** [comment]
This looks good, doubly so for a first effort at rspec.  I had figured managing ipmi would need to be done as a native type.  Thanks for contributing!

**Pull request merged**
