### PR TITLE
F/bmc lan conf fact

### PR DESCRIPTION
**Pull request by faxm0dem**
This adds two facts to the module.
I chose to pull in the `freeipmi` package because it's much more robust and simple to pull BMC parameters from the KCS interface.
Please tell me what you think

### CODE REVIEW

**Comment by jhoblitt** [comment]
It's great that there's interest in adding facts to this module!  The `bmc_lan_conf` fact in this PR is similar to the unstructured facts proposed in #12.  

@domq - Do you have a requirement for unstructured facts?  I'll note that I've experienced issues in the past with foreman's handling of structured facts.  Do you have systems with multiple BMCs?  I haven't had one myself in years but in the past managed Intel brand motherboards with both an onboard BMC and an add-on RMM module.

**Comment by faxm0dem** [comment]
Sorry about the dupe I was sure I checked for PRs beforehand.
The foreman's compliance seems very cool. However I strongly believe freeipmi is more portable, robust (parsing is simpler) and much easier to control e.g. for later features like setting the lan params in puppet.
I suggest we merge both PR's best bits

**Comment by elisiano** [comment]
Please bear in mind that a single BMC can have multiple lan channels (in my experience Intel's RMMs).
Example of multiple channels (notice Medium Type):
```
# bmc-info 
Device ID:         33
Device Revision:   1
Firmware Revision: 1.21
                   [Device Available (normal operation)]
IPMI Version:      2.0
Additional Device Support:
                   [Sensor Device]
                   [SDR Repository Device]
                   [SEL Device]
                   [FRU Inventory Device]
                   [IPMB Event Receiver]
                   [IPMB Event Generator]
                   [Chassis Device]
Manufacturer ID:   343
Product ID:        92
Aux Firmware Revision Info: Boot Code v01.17, PIA v96.17
Channel Information:
       Channel No: 0
      Medium Type: IPMB (I2C)
    Protocol Type: IPMB-1.0
       Channel No: 1
      Medium Type: 802.3 LAN
    Protocol Type: IPMB-1.0
       Channel No: 2
      Medium Type: 802.3 LAN
    Protocol Type: IPMB-1.0
       Channel No: 3
      Medium Type: 802.3 LAN
    Protocol Type: IPMB-1.0
       Channel No: 6
      Medium Type: IPMB (I2C)
    Protocol Type: IPMB-1.0
       Channel No: 7
      Medium Type: System Interface (KCS, SMIC, or BT)
    Protocol Type: KCS
```
As opposed to single LAN channel:
```
# bmc-info 
Device ID:         32
Device Revision:   1
                   [SDR Support]
Firmware Revision: 3.58
                   [Device Available (normal operation)]
IPMI Version:      2.0
Additional Device Support:
                   [Sensor Device]
                   [SDR Repository Device]
                   [SEL Device]
                   [FRU Inventory Device]
                   [IPMB Event Receiver]
                   [IPMB Event Generator]
                   [Chassis Device]
Manufacturer ID:   7244
Product ID:        12882
Aux Firmware Revision Info: 0h
Channel Information:
       Channel No: 0
      Medium Type: IPMB (I2C)
    Protocol Type: IPMB-1.0
       Channel No: 1
      Medium Type: 802.3 LAN
    Protocol Type: IPMB-1.0
       Channel No: 5
      Medium Type: System Interface (KCS, SMIC, or BT)
    Protocol Type: KCS
       Channel No: 6
      Medium Type: IPMB (I2C)
    Protocol Type: IPMB-1.0
```

So I believe that this should be taken into consideration when exporting facts (especially since, like in our case, it's not always the first interface to be configured).
The method used in this PR (`bmc-config --checkout --section Lan_Conf --disable-auto-probe`) shows only the first interface:
```
# bmc-config --checkout --section Lan_Conf --disable-auto-probe
#
# Section Lan_Conf Comments 
#
# In the Lan_Conf section, typical networking configuration is setup. Most users 
# will choose to set "Static" for the "IP_Address_Source" and set the 
# appropriate "IP_Address", "MAC_Address", "Subnet_Mask", etc. for the machine. 
#
Section Lan_Conf
        ## Possible values: Unspecified/Static/Use_DHCP/Use_BIOS/Use_Others
        IP_Address_Source                             Static
        ## Give valid IP address
        IP_Address                                    0.0.0.0
        ## Give valid MAC address
        MAC_Address                                   00:1E:67:58:97:56
        ## Give valid Subnet Mask
        Subnet_Mask                                   0.0.0.0
        ## Give valid IP address
        Default_Gateway_IP_Address                    0.0.0.0
        ## Give valid MAC address
        Default_Gateway_MAC_Address                   00:00:00:00:00:00
        ## Give valid IP address
        Backup_Gateway_IP_Address                     0.0.0.0
        ## Give valid MAC address
        Backup_Gateway_MAC_Address                    00:00:00:00:00:00
        ## Give valid unsigned number
        Vlan_id                                       0
        ## Possible values: Yes/No
        Vlan_Id_Enable                                No
        ## Give valid unsigned number
        Vlan_Priority                                 0
EndSection
```
Whereas looping over channels with ipmitool (like the other PR does) shows all the configured interfaces:
```
# for i in {1..3}; do echo "==== Channel $i ===="; ipmitool lan print $i; done                                                                                                      
==== Channel 1 ====
Set in Progress         : Set Complete
Auth Type Support       : MD5 PASSWORD 
Auth Type Enable        : Callback : MD5 PASSWORD 
                        : User     : MD5 PASSWORD 
                        : Operator : MD5 PASSWORD 
                        : Admin    : MD5 PASSWORD 
                        : OEM      : 
IP Address Source       : Static Address
IP Address              : 0.0.0.0
Subnet Mask             : 0.0.0.0
MAC Address             : 00:1e:67:58:97:56
SNMP Community String   : public
IP Header               : TTL=0x00 Flags=0x00 Precedence=0x00 TOS=0x00
BMC ARP Control         : ARP Responses Enabled, Gratuitous ARP Disabled
Gratituous ARP Intrvl   : 0.0 seconds
Default Gateway IP      : 0.0.0.0
Default Gateway MAC     : 00:00:00:00:00:00
Backup Gateway IP       : 0.0.0.0
Backup Gateway MAC      : 00:00:00:00:00:00
802.1q VLAN ID          : Disabled
802.1q VLAN Priority    : 0
RMCP+ Cipher Suites     : 0,1,2,3,4,6,7,8,9,11,12,13,15,16,17,18
Cipher Suite Priv Max   : caaaaaaaaaaaaaa
                        :     X=Cipher Suite Unused
                        :     c=CALLBACK
                        :     u=USER
                        :     o=OPERATOR
                        :     a=ADMIN
                        :     O=OEM
==== Channel 2 ====
Set in Progress         : Set Complete
Auth Type Support       : MD5 PASSWORD 
Auth Type Enable        : Callback : MD5 PASSWORD 
                        : User     : MD5 PASSWORD 
                        : Operator : MD5 PASSWORD 
                        : Admin    : MD5 PASSWORD 
                        : OEM      : 
IP Address Source       : Static Address
IP Address              : 0.0.0.0
Subnet Mask             : 0.0.0.0
MAC Address             : 00:1e:67:58:97:56
SNMP Community String   : public
IP Header               : TTL=0x00 Flags=0x00 Precedence=0x00 TOS=0x00
BMC ARP Control         : ARP Responses Enabled, Gratuitous ARP Disabled
Gratituous ARP Intrvl   : 0.0 seconds
Default Gateway IP      : 0.0.0.0
Default Gateway MAC     : 00:00:00:00:00:00
Backup Gateway IP       : 0.0.0.0
Backup Gateway MAC      : 00:00:00:00:00:00
802.1q VLAN ID          : Disabled
802.1q VLAN Priority    : 0
RMCP+ Cipher Suites     : 0,1,2,3,4,6,7,8,9,11,12,13,15,16,17,18
Cipher Suite Priv Max   : caaaaaaaaaaaaaa
                        :     X=Cipher Suite Unused
                        :     c=CALLBACK
                        :     u=USER
                        :     o=OPERATOR
                        :     a=ADMIN
                        :     O=OEM
==== Channel 3 ====
Set in Progress         : Set Complete
Auth Type Support       : MD5 PASSWORD 
Auth Type Enable        : Callback : MD5 PASSWORD 
                        : User     : MD5 PASSWORD 
                        : Operator : MD5 PASSWORD 
                        : Admin    : MD5 PASSWORD 
                        : OEM      : 
IP Address Source       : DHCP Address
IP Address              : 10.4.64.48
Subnet Mask             : 255.255.240.0
MAC Address             : 00:1e:67:58:97:58
SNMP Community String   : public
IP Header               : TTL=0x00 Flags=0x00 Precedence=0x00 TOS=0x00
BMC ARP Control         : ARP Responses Enabled, Gratuitous ARP Disabled
Gratituous ARP Intrvl   : 0.0 seconds
Default Gateway IP      : 10.4.64.1
Default Gateway MAC     : 00:00:00:00:00:00
Backup Gateway IP       : 0.0.0.0
Backup Gateway MAC      : 00:00:00:00:00:00
802.1q VLAN ID          : Disabled
802.1q VLAN Priority    : 0
RMCP+ Cipher Suites     : 0,1,2,3,4,6,7,8,9,11,12,13,15,16,17,18
Cipher Suite Priv Max   : caaaaaaaaaaaaaa
                        :     X=Cipher Suite Unused
                        :     c=CALLBACK
                        :     u=USER
                        :     o=OPERATOR
                        :     a=ADMIN
                        :     O=OEM
```

**Comment by jhoblitt** [comment]
Alternative PR #12 (merged as #16) has been merged.  Hopefully, any missing functionality can be worked into those new facts.

**Pull request closed without merging**
