### PR TITLE
Add Debian based os support

### PR DESCRIPTION
**Pull request by petems**
* Tested on Ubuntu 16.04 HP Proliant 8 server:

```
root@homebox:~# puppet apply -e 'include ipmi'
Notice: Compiled catalog for homebox.home in environment production in 0.36 seconds
Notice: /Stage[main]/Ipmi::Install/Package[openipmi]/ensure: created
Notice: /Stage[main]/Ipmi::Install/Package[ipmitool]/ensure: created
Notice: /Stage[main]/Ipmi::Config/Augeas[/etc/default/openipmi]/returns: executed successfully
Notice: /Stage[main]/Ipmi::Service::Ipmi/Service[openipmi]: Triggered 'refresh' from 1 events
Notice: /Stage[main]/Ipmi::Service::Ipmievd/Service[ipmievd]: Triggered 'refresh' from 1 events
Notice: Applied catalog in 12.66 seconds
root@homebox:~# ipmitool -I open chassis power status
Chassis Power is on
root@homebox:~# facter os.family
Debian
```

### CODE REVIEW

**Comment by jhoblitt** [comment]
Looks like the `metadata.json` change has a typo.

**Comment by petems** [comment]
@jhoblitt Just fixed, thanks to JSON lint 👍

**Comment by jhoblitt** [comment]
@petems Your still my hero. :+1:

**Comment by petems** [comment]
Thanks for the super quick response 💃

**Comment by jhoblitt** [comment]
Shipped as `2.3.0`.

**Pull request merged**
